import duality_theory_topological_vector_spaces_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace duality_theory_topological_vector_spaces_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end duality_theory_topological_vector_spaces_theorem_canonical_lane_mathlib
end HautevilleHouse
